### ISSUE TITLE
Is this code usable in production?

### ISSUE THREAD

**Issue by costa100** [DavidGregory084/vertices#10]
Hi,

This is a quick question, not an issue - is this code usable in production? Also, did you do any performance benchmarks? I would be curious to find how it fares against the current vertx-lang-scala used in 3.9.x? I heard only good things about Monix. 

Thanks 
PS. Sorry for creating this issue - I did not find another way to reach you.

**Comment by DavidGregory084** [comment]
No problem @costa100!

I think that whether or not you use this code in production kind of depends on the project you are working on and how much risk you can accept on that project. For me it is only a hobby project and I have not had a great deal of cause to use it in production since I no longer work at a company which uses Vert.x in production. As a result I haven't had any need of performance benchmarks either.

The library simply generates wrapper code around the existing Vert.x APIs so the actual complexity of it is quite low and most of the performance characteristics of the library depend upon Vert.x and Monix.

I have used it for some simple projects like [this](https://github.com/DavidGregory084/il2ssd2/blob/master/server/src/main/scala/il2ssd/Server.scala) one, which talks to a React webapp over a websocket but nothing more serious than that.

**Comment by costa100** [comment]
Thanks for getting back to me! I will close it.
